language: python
sudo: false

addons:
  apt:
    packages:
      - libzzip-dev

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA --luarocks latest
  - source env/bin/activate

install:
  - luarocks make

before_script:
  - luarocks install busted

script:
  - busted
